### ISSUE TITLE
Add more IPNS record tests based on IPIP-428

### ISSUE THREAD

**Issue by lidel** [ipfs/gateway-conformance#144]
Ref. https://github.com/ipfs/specs/pull/428 tldr: we should have `.ipns-record` files with fixtures for:

- [ ]  V1-only → record invalid (gateway returns 5XX error)
- [ ] V1+V2 (both signatures valid) → record valid, HTTP 200
- [ ]  V1+V2 (both signatures valid, but 'value' is different in V1 pb) → record invalid (gateway returns 5XX error)
- [ ] V1+V2 (only signatureV1 valid) → record invalid (gateway returns 5XX error)
- [ ] V1+V2 (only signatureV2 valid) → record valid, HTTP 200
- [ ] V2-only (no V1 fields) → record valid, HTTP 200 
- [ ] update [IPIP-428](https://github.com/ipfs/specs/pull/428) and include links to mentioned fixtures from this PR

This will be an extremely useful resource for anyone trying to implement IPNS, as they would  be able to either run gateway-conformance, or at least reuse related fixtures.

**Comment by lidel** [comment]
@hacdias would you be able to tackle this before diving into unixfs?
(since you've done GO and JS implementation of IPIP-428 and have the relevant context)

**Comment by hacdias** [comment]
@lidel I just made a script to generate all these cases. However, none of the invalid ones will be able to be tested with Kubo. Why? Kubo will never put them in the routing table as they'll be immediately discarded since they are invalid. Therefore, how are we supposed to use them in gateway conformance?

We can still use them for `js-ipns`, `boxo/ipns` and for the IPIP. However, I can't see how we'll use them here.
